# Generated by Django 5.2.13 on 2026-05-06 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('taxonomy', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_code', models.CharField(max_length=100, unique=True)),
                ('local_code', models.CharField(blank=True, max_length=100)),
                ('box_number', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('lost', 'Lost'), ('stopped', 'Stopped')], default='active', max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('entered_on', models.DateField(blank=True, null=True)),
                ('volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='organizations.organization')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.origin')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='taxonomy.strain')),
            ],
        ),
        migrations.CreateModel(
            name='BoxTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cultures.box')),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_box_transfers', to='organizations.organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_box_transfers', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='SubcultureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('parent_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_subculture_events', to='cultures.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ThermalZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(choices=[('cabinet', 'Cabinet'), ('incubator', 'Incubator'), ('tank', 'Tank'), ('other', 'Other')], default='cabinet', max_length=30)),
                ('target_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_zones', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('qr', 'QR code'), ('nfc', 'NFC'), ('rfid', 'RFID')], default='qr', max_length=20)),
                ('code', models.CharField(max_length=160, unique=True)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cultures.box')),
                ('thermal_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cultures.thermalzone')),
            ],
        ),
        migrations.CreateModel(
            name='BoxMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cultures.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_thermal_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_box_movements', to='cultures.thermalzone')),
                ('to_thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_box_movements', to='cultures.thermalzone')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='BoxLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cultures.box')),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_locations', to='cultures.thermalzone')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='thermal_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='cultures.thermalzone'),
        ),
        migrations.CreateModel(
            name='BoxLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('subculture', 'Subculture'), ('sexual_reproduction', 'Sexual reproduction'), ('historical_import', 'Historical import'), ('other', 'Other')], default='subculture', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('child_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_lineages', to='cultures.box')),
                ('parent_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_lineages', to='cultures.box')),
                ('subculture_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineages', to='cultures.subcultureevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent_box', 'child_box'), name='unique_box_lineage'), models.CheckConstraint(condition=models.Q(('parent_box', models.F('child_box')), _negated=True), name='box_lineage_parent_differs_from_child')],
            },
        ),
        migrations.AddConstraint(
            model_name='thermalzone',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_thermal_zone_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='identificationtag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('box__isnull', False), ('thermal_zone__isnull', True)), models.Q(('box__isnull', True), ('thermal_zone__isnull', False)), _connector='OR'), name='identification_tag_targets_one_object'),
        ),
        migrations.AddIndex(
            model_name='boxlocation',
            index=models.Index(fields=['box', 'starts_at'], name='cultures_bo_box_id_bec850_idx'),
        ),
        migrations.AddIndex(
            model_name='boxlocation',
            index=models.Index(fields=['thermal_zone', 'starts_at'], name='cultures_bo_thermal_3f3afb_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['organization', 'status'], name='cultures_bo_organiz_9519bc_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['global_code'], name='cultures_bo_global__27ac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['local_code'], name='cultures_bo_local_c_9707d4_idx'),
        ),
    ]
