# Generated by Django 5.2.13 on 2026-05-04 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('biologique', 'Biologique'), ('temperature', 'Température'), ('salinite', 'Salinité'), ('repiquage', 'Repiquage'), ('autre', 'Autre')], max_length=40)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Vigilance'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AnomalieThermique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temperature_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ecart_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Vigilance'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ExportDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('inventaire', 'Inventaire'), ('releves', 'Relevés biologiques'), ('temperatures', 'Températures'), ('reglementaire', 'Réglementaire'), ('taxonomie', 'Taxonomie')], max_length=40)),
                ('format_export', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10)),
                ('filtres', models.JSONField(blank=True, default=dict)),
                ('nom_fichier', models.CharField(blank=True, max_length=220)),
                ('date_export', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_export'],
            },
        ),
        migrations.CreateModel(
            name='ImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=220)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('importe', 'Importé'), ('erreur', 'Erreur')], default='brouillon', max_length=30)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180, unique=True)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('pays', models.CharField(blank=True, max_length=120)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('archivage', 'Archivage'), ('saisie', 'Saisie'), ('repiquage', 'Repiquage'), ('transfert', 'Transfert'), ('import', 'Import'), ('export', 'Export'), ('scan', 'Scan'), ('connexion', 'Connexion')], max_length=40)),
                ('objet_type', models.CharField(blank=True, max_length=80)),
                ('objet_id', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='LigneImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('donnees_brutes', models.JSONField(default=dict)),
                ('est_valide', models.BooleanField(default=False)),
                ('erreurs', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['numero_ligne'],
            },
        ),
        migrations.CreateModel(
            name='LocalisationBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MesureTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateTimeField()),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('donnees_brutes', models.JSONField(blank=True, default=dict)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_mesure'],
            },
        ),
        migrations.CreateModel(
            name='MouvementBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField(default=django.utils.timezone.localdate)),
                ('type_observation', models.CharField(choices=[('generale', 'Générale'), ('contamination', 'Contamination'), ('repiquage_a_prevoir', 'Repiquage à prévoir'), ('mortalite', 'Mortalité'), ('autre', 'Autre')], default='generale', max_length=40)),
                ('commentaire', models.TextField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_observation', '-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='ParenteBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('repiquage', 'Repiquage'), ('reproduction', 'Reproduction sexuée'), ('import_historique', 'Import historique'), ('autre', 'Autre')], default='repiquage', max_length=40)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveSalinite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('salinite_psu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_releve'],
            },
        ),
        migrations.CreateModel(
            name='Repiquage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repiquage', models.DateField(default=django.utils.timezone.localdate)),
                ('motif', models.CharField(blank=True, max_length=180)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_repiquage'],
            },
        ),
        migrations.CreateModel(
            name='Sonde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('type_sonde', models.CharField(choices=[('lorawan', 'LoRaWAN'), ('iminilide', 'iMinilide'), ('manuel', 'Saisie manuelle'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('emplacement', models.CharField(blank=True, max_length=180)),
                ('est_active', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tag', models.CharField(choices=[('qr', 'QR code'), ('nfc', 'NFC'), ('rfid', 'RFID')], default='qr', max_length=20)),
                ('code', models.CharField(max_length=160, unique=True)),
                ('url', models.URLField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nombre_mesures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='appartenanceutilisateur',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='appartenanceutilisateur',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appartenanceutilisateur',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boite',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boite',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provenance'),
        ),
        migrations.AddField(
            model_name='boite',
            name='raison_arret',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='boite',
            name='volume_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='espece',
            name='code_genre_espece',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='espece',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='espece',
            name='est_decrite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='espece',
            name='worms_aphia_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='date_evenement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='techniciens',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='provenance',
            name='technique',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='relevebiologique',
            name='nombre_strobiles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relevebiologique',
            name='vigilance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='souche',
            name='code_provenance',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='souche',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='structure',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='pays',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='structure',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='ville',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='core.taxon'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='worms_aphia_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='zonethermique',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='boite',
            index=models.Index(fields=['structure', 'statut'], name='core_boite_structu_a32837_idx'),
        ),
        migrations.AddIndex(
            model_name='boite',
            index=models.Index(fields=['global_code'], name='core_boite_global__2d8997_idx'),
        ),
        migrations.AddIndex(
            model_name='boite',
            index=models.Index(fields=['code_local'], name='core_boite_code_lo_f4bd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='relevebiologique',
            index=models.Index(fields=['boite', 'date_releve'], name='core_releve_boite_i_db63fb_idx'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='boite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.boite'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='resolue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='zone_thermique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='anomaliethermique',
            name='zone_thermique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_thermiques', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure'),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provenance',
            name='institution_partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institutionpartenaire'),
        ),
        migrations.AddField(
            model_name='journalaction',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.structure'),
        ),
        migrations.AddField(
            model_name='journalaction',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneimportexcel',
            name='import_excel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.importexcel'),
        ),
        migrations.AddField(
            model_name='localisationboite',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='core.boite'),
        ),
        migrations.AddField(
            model_name='localisationboite',
            name='zone_thermique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='mesuretemperature',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementboite',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.boite'),
        ),
        migrations.AddField(
            model_name='mouvementboite',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementboite',
            name='zone_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_arrivee', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='mouvementboite',
            name='zone_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_depart', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='observation',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.boite'),
        ),
        migrations.AddField(
            model_name='observation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parenteboite',
            name='boite_enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liens_parents', to='core.boite'),
        ),
        migrations.AddField(
            model_name='parenteboite',
            name='boite_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liens_enfants', to='core.boite'),
        ),
        migrations.AddField(
            model_name='relevesalinite',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relevesalinite',
            name='zone_thermique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_salinite', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='repiquage',
            name='boite_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repiquages_sources', to='core.boite'),
        ),
        migrations.AddField(
            model_name='repiquage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parenteboite',
            name='repiquage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_parentes', to='core.repiquage'),
        ),
        migrations.AddField(
            model_name='sonde',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure'),
        ),
        migrations.AddField(
            model_name='sonde',
            name='zone_thermique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondes', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='mesuretemperature',
            name='sonde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.sonde'),
        ),
        migrations.AddField(
            model_name='tagidentification',
            name='boite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.boite'),
        ),
        migrations.AddField(
            model_name='tagidentification',
            name='zone_thermique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.zonethermique'),
        ),
        migrations.AddField(
            model_name='temperaturejournaliere',
            name='zone_thermique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures_journalieres', to='core.zonethermique'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['structure', 'type_alerte', 'date_creation'], name='core_alerte_structu_faadd0_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaction',
            index=models.Index(fields=['structure', 'date_action'], name='core_journa_structu_f79354_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaction',
            index=models.Index(fields=['action', 'date_action'], name='core_journa_action_929652_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneimportexcel',
            constraint=models.UniqueConstraint(fields=('import_excel', 'numero_ligne'), name='unique_ligne_par_import_excel'),
        ),
        migrations.AddIndex(
            model_name='localisationboite',
            index=models.Index(fields=['boite', 'date_debut'], name='core_locali_boite_i_d2e96b_idx'),
        ),
        migrations.AddIndex(
            model_name='localisationboite',
            index=models.Index(fields=['zone_thermique', 'date_debut'], name='core_locali_zone_th_56eb98_idx'),
        ),
        migrations.AddConstraint(
            model_name='relevesalinite',
            constraint=models.UniqueConstraint(fields=('zone_thermique', 'date_releve'), name='unique_salinite_par_zone_date'),
        ),
        migrations.AddConstraint(
            model_name='parenteboite',
            constraint=models.UniqueConstraint(fields=('boite_parent', 'boite_enfant'), name='unique_lien_parente_boite'),
        ),
        migrations.AddConstraint(
            model_name='parenteboite',
            constraint=models.CheckConstraint(condition=models.Q(('boite_parent', models.F('boite_enfant')), _negated=True), name='parente_boite_parent_different_enfant'),
        ),
        migrations.AddConstraint(
            model_name='sonde',
            constraint=models.UniqueConstraint(fields=('structure', 'code'), name='unique_sonde_par_structure'),
        ),
        migrations.AddIndex(
            model_name='mesuretemperature',
            index=models.Index(fields=['date_mesure'], name='core_mesure_date_me_cf7d95_idx'),
        ),
        migrations.AddConstraint(
            model_name='mesuretemperature',
            constraint=models.UniqueConstraint(fields=('sonde', 'date_mesure'), name='unique_mesure_temperature_par_sonde_date'),
        ),
        migrations.AddConstraint(
            model_name='tagidentification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boite__isnull', False), ('zone_thermique__isnull', True)), models.Q(('boite__isnull', True), ('zone_thermique__isnull', False)), _connector='OR'), name='tag_cible_unique_boite_ou_zone'),
        ),
        migrations.AddConstraint(
            model_name='temperaturejournaliere',
            constraint=models.UniqueConstraint(fields=('zone_thermique', 'date'), name='unique_temperature_journaliere_par_zone_date'),
        ),
    ]
