# Generated by Django 5.2.13 on 2026-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archivée'), ('lost', 'Perdue'), ('stopped', 'Arrêtée')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='boxlineage',
            name='relationship_type',
            field=models.CharField(choices=[('subculture', 'Repiquage'), ('sexual_reproduction', 'Reproduction sexuée'), ('historical_import', 'Import historique'), ('other', 'Autre')], default='subculture', max_length=40),
        ),
        migrations.AlterField(
            model_name='boxtransfer',
            name='status',
            field=models.CharField(choices=[('planned', 'Prévu'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='thermalzone',
            name='zone_type',
            field=models.CharField(choices=[('cabinet', 'Armoire'), ('incubator', 'Étuve'), ('tank', 'Tank'), ('other', 'Autre')], default='cabinet', max_length=30),
        ),
    ]
