# Generated by Django 5.2.13 on 2026-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_alter_box_status_alter_boxlineage_relationship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalzone',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
