# Generated by Django 5.2.13 on 2026-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0003_thermalzone_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalzone',
            name='salinity_psu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
