# Generated by Django 5.2.17 on 2026-08-27 15:10

import django.db.models.deletion
from django.db import migrations, models


def convert_legacy_box_statuses(apps, schema_editor):
    Box = apps.get_model('cultures', 'Box')
    Box.objects.filter(status__in=['archived', 'lost', 'stopped']).update(status='inactive')


def restore_compatible_legacy_statuses(apps, schema_editor):
    Box = apps.get_model('cultures', 'Box')
    Box.objects.filter(status='inactive').update(status='archived')
    Box.objects.filter(status='pending_review').update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0006_boxtransferimport'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='deactivated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='stop_reason_missing_from_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='end_date_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            convert_legacy_box_statuses,
            restore_compatible_legacy_statuses,
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('pending_review', 'À vérifier'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
        migrations.CreateModel(
            name='BoxInventoryInitialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('box_count', models.PositiveIntegerField()),
                ('previous_status_counts', models.JSONField(default=dict)),
                ('selection_hash', models.CharField(max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='box_inventory_initialization', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='boxlocation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date_unknown', False), ('ends_at__isnull', True), _connector='OR'), name='box_location_unknown_end_has_no_date'),
        ),
    ]
