# Generated by Django 5.2.17 on 2026-10-02 12:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0007_box_inventory_lifecycle'),
        # The FK needs only the Organization table, not its portable_id column.
                # Keep historical cross-app migration targets independently reachable.
                ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_institution_id', models.UUIDField(editable=False)),
                ('source_institution_name', models.CharField(editable=False, max_length=150)),
                ('destination_institution_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('destination_institution_name', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('protocol_major', models.PositiveIntegerField(default=2, editable=False)),
                ('protocol_minor', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_envelopes', to=settings.AUTH_USER_MODEL)),
                ('source_organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_envelopes', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source_box_code', models.CharField(editable=False, max_length=100)),
                ('source_strain_code', models.CharField(editable=False, max_length=80)),
                ('species_scientific_name', models.CharField(editable=False, max_length=150)),
                ('global_strain_id', models.UUIDField(editable=False)),
                ('declared_polyp_quantity', models.PositiveIntegerField(editable=False)),
                ('envelope', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cultures.transferenvelope')),
                ('source_box', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='cultures.box')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('envelope', 'item_id'), name='unique_transfer_item_per_envelope'), models.CheckConstraint(condition=models.Q(('declared_polyp_quantity__gte', 0)), name='transfer_item_quantity_nonnegative')],
            },
        ),
    ]
