# Generated by Django 5.2.17 on 2026-10-04 14:04

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0009_portable_lineage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCodeNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('high_water', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubcultureAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('allocated_polyps', models.PositiveIntegerField()),
                ('child_state_sequence', models.PositiveBigIntegerField(default=1, editable=False)),
                ('child_global_code', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='polyp_state_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='allocated_polyp_count',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='author_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='occurred_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='parent_polyp_count_after',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='parent_polyp_count_before',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='parent_state_sequence',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcultureevent',
            name='parent_state_snapshot',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='subcultureevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_polyp_count__isnull', True), ('occurred_at__isnull', True), ('parent_polyp_count_after__isnull', True), ('parent_polyp_count_before__isnull', True), ('parent_state_sequence__isnull', True), ('parent_state_snapshot__isnull', True)), models.Q(('allocated_polyp_count__isnull', False), ('occurred_at__isnull', False), ('parent_polyp_count_after__isnull', False), ('parent_polyp_count_before', django.db.models.expressions.CombinedExpression(models.F('allocated_polyp_count'), '+', models.F('parent_polyp_count_after'))), ('parent_polyp_count_before__isnull', False), ('parent_state_sequence__isnull', False), ('parent_state_snapshot__isnull', False)), _connector='OR'), name='subculture_absolute_polyp_balance'),
        ),
        migrations.AddField(
            model_name='subcultureallocation',
            name='child_box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subculture_initialization', to='cultures.box'),
        ),
        migrations.AddField(
            model_name='subcultureallocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cultures.subcultureevent'),
        ),
        migrations.AddConstraint(
            model_name='subcultureallocation',
            constraint=models.UniqueConstraint(fields=('event', 'position'), name='unique_subculture_allocation_position'),
        ),
    ]
