# Generated by Django 5.2.17 on 2026-10-05 08:06

from importlib import import_module

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


guards = import_module("apps.cultures.migrations.0011_protect_subculture_history")


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0011_protect_subculture_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SQLite table rebuilds discard triggers; reinstall the existing guards.
    operations = [
        migrations.RunPython(guards.remove_guards, guards.install_guards),
        migrations.RemoveConstraint(
            model_name='subcultureevent',
            name='subculture_absolute_polyp_balance',
        ),
        migrations.AlterField(
            model_name='subcultureallocation',
            name='allocated_polyps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='subcultureevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_polyp_count__isnull', True), ('occurred_at__isnull', True), ('parent_polyp_count_after__isnull', True), ('parent_polyp_count_before__isnull', True), ('parent_state_sequence__isnull', True), ('parent_state_snapshot__isnull', True)), models.Q(('allocated_polyp_count__isnull', False), ('occurred_at__isnull', False), ('parent_polyp_count_after__isnull', False), ('parent_polyp_count_before', django.db.models.expressions.CombinedExpression(models.F('allocated_polyp_count'), '+', models.F('parent_polyp_count_after'))), ('parent_polyp_count_before__isnull', False), ('parent_state_sequence__isnull', False), ('parent_state_snapshot__isnull', False)), models.Q(('allocated_polyp_count__isnull', True), ('occurred_at__isnull', False), ('parent_polyp_count_after__isnull', True), ('parent_polyp_count_before__isnull', False), ('parent_state_sequence__isnull', False), ('parent_state_snapshot__isnull', False)), _connector='OR'), name='subculture_absolute_polyp_balance'),
        ),
        migrations.RunPython(guards.install_guards, guards.remove_guards),
    ]
