"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env if present.
load_dotenv(BASE_DIR / ".env")


def env_flag(name, default=False):
    """Read a boolean from the environment ("1"/"true"/"yes" are all true)."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Django forces DEBUG=False while running tests, but this module is imported
# before that happens: without this flag the production hardening below would
# turn on SECURE_SSL_REDIRECT and every test request would get a 301.
RUNNING_TESTS = "test" in sys.argv

# Defaults to False so that a forgotten environment variable in production is
# safe (no debug pages, no source leak) rather than dangerous. Development sets
# DJANGO_DEBUG=1 in backend/.env.
DEBUG = env_flag("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In production the key MUST come from the environment. There is deliberately no
# fallback: a hardcoded key committed to the repository would let anyone forge
# sessions. Startup fails loudly instead of running insecurely.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG or RUNNING_TESTS:
        SECRET_KEY = "django-insecure-development-only-key-do-not-use-in-production"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off. "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(64))\""
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:5173,http://localhost:5173,https://*.trycloudflare.com",
    ).split(",")
    if origin.strip()
]

# Public base URL embedded in QR codes (no trailing slash). A scanned QR code
# points to {PUBLIC_BASE_URL}/bac/<id>/, so this must be the address the
# biologist's phone can reach: the address of the *app* (production domain, or
# the Vite dev server), not of the Django server. Pointing it at Django used to
# make a scanned code land on a bare server-rendered page instead of the app.
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "http://localhost:5173").rstrip("/")


# -- Security -----------------------------------------------------------------

# Always on: the app is never displayed inside a frame, so refuse to be framed
# (clickjacking) and never let the browser guess a content type.
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

# The session cookie is never read from JavaScript.
SESSION_COOKIE_HTTPONLY = True

# The CSRF cookie, on the contrary, MUST stay readable from JavaScript: the
# React app reads it to send the X-CSRFToken header. Setting
# CSRF_COOKIE_HTTPONLY = True here would silently break every login.
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Production only. In development everything is served over plain HTTP on
# localhost, so forcing HTTPS would make the app unreachable.
if not DEBUG and not RUNNING_TESTS:
    # TLS is terminated by the platform (Render, Railway, Fly, nginx...), which
    # forwards the original scheme in this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SECURE_SSL_REDIRECT = env_flag("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS tells browsers to only ever use HTTPS for this domain. It is cached
    # by the browser, so a too-long value is hard to undo: start at one day and
    # raise it (via the env var) once HTTPS is proven stable.
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "86400"))
    # Off by default: it would also force HTTPS on every sibling subdomain of
    # the organisation, which we do not control.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
    )
    SECURE_HSTS_PRELOAD = env_flag("DJANGO_SECURE_HSTS_PRELOAD", default=False)


# Application definition

LOCAL_APPS = [
    "apps.accounts.apps.AccountsConfig",
    "apps.organizations.apps.OrganizationsConfig",
    "apps.taxonomy.apps.TaxonomyConfig",
    "apps.cultures.apps.CulturesConfig",
    "apps.measurements.apps.MeasurementsConfig",
    "apps.exports.apps.ExportsConfig",
    "apps.audit.apps.AuditConfig",
]

INSTALLED_APPS = [
    *LOCAL_APPS,
    "rest_framework",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "apps.accounts.middleware.UserInterfaceLanguageMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER", ""),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "OPTIONS": {"sslmode": os.getenv("POSTGRES_SSLMODE", "prefer")},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Lifetime of a "forgot password" link. Django's default is 3 days, which is a
# long window for a link that grants account access; one hour is enough to read
# an email and still limits exposure if the mailbox is compromised later.
PASSWORD_RESET_TIMEOUT = int(os.getenv("DJANGO_PASSWORD_RESET_TIMEOUT", "3600"))

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# In development, emails are printed in the terminal. Production should set a
# real SMTP backend through environment variables.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Polypbase <no-reply@polypbase.local>")

# The React app owns the UI: authentication redirects must land there, never on
# a server-rendered page (the old HTML pages have been removed).
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 50,
}
