# Generated by Django 5.2.13 on 2026-04-30 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_code', models.CharField(max_length=100, unique=True)),
                ('code_local', models.CharField(blank=True, max_length=100)),
                ('numero_boite', models.CharField(max_length=80)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('perdue', 'Perdue'), ('arretee', 'Arrêtée')], default='active', max_length=30)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_scientifique', models.CharField(max_length=150, unique=True)),
                ('nom_commun', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_provenance', models.CharField(choices=[('prelevement', 'Prélèvement'), ('reproduction', 'Reproduction'), ('don', 'Don'), ('echange', 'Échange'), ('inconnue', 'Inconnue')], default='inconnue', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('institution_origine', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('rang', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('nombre_polypes', models.PositiveIntegerField(default=0)),
                ('nombre_ephyres', models.PositiveIntegerField(default=0)),
                ('etat_culture', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('mort', 'Mort'), ('non_precise', 'Non précisé')], default='non_precise', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_biologiques', to='core.boite')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_releve', '-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='Souche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('commentaire', models.TextField(blank=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.espece')),
                ('provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provenance')),
            ],
        ),
        migrations.AddField(
            model_name='boite',
            name='souche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.souche'),
        ),
        migrations.AddField(
            model_name='boite',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.structure'),
        ),
        migrations.CreateModel(
            name='AppartenanceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure')),
            ],
        ),
        migrations.AddField(
            model_name='espece',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxon'),
        ),
        migrations.CreateModel(
            name='ZoneThermique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type_zone', models.CharField(choices=[('armoire', 'Armoire'), ('etuve', 'Étuve'), ('bac', 'Bac'), ('autre', 'Autre')], default='armoire', max_length=30)),
                ('temperature_consigne', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structure')),
            ],
        ),
        migrations.AddField(
            model_name='boite',
            name='zone_thermique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zonethermique'),
        ),
        migrations.AddConstraint(
            model_name='souche',
            constraint=models.UniqueConstraint(fields=('espece', 'code'), name='unique_souche_par_espece'),
        ),
        migrations.AddConstraint(
            model_name='appartenanceutilisateur',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'structure'), name='unique_utilisateur_structure'),
        ),
        migrations.AddConstraint(
            model_name='zonethermique',
            constraint=models.UniqueConstraint(fields=('structure', 'nom'), name='unique_zone_par_structure'),
        ),
    ]
