# Generated by Django 5.2.13 on 2026-05-06 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('inventory', 'Inventory'), ('measurements', 'Measurements'), ('temperatures', 'Temperatures'), ('regulatory', 'Regulatory'), ('taxonomy', 'Taxonomy')], max_length=40)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(blank=True, max_length=220)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('imported', 'Imported'), ('error', 'Error')], default='draft', max_length=30)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_imports', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('excel_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='exports.excelimport')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('excel_import', 'row_number'), name='unique_row_per_excel_import')],
            },
        ),
    ]
