# Generated by Django 5.2.13 on 2026-05-06 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('observation_type', models.CharField(choices=[('general', 'General'), ('contamination', 'Contamination'), ('subculture_needed', 'Subculture needed'), ('mortality', 'Mortality'), ('other', 'Other')], default='general', max_length=40)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cultures.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('probe_type', models.CharField(choices=[('lorawan', 'LoRaWAN'), ('iminilide', 'iMinilide'), ('manual', 'Manual entry'), ('other', 'Other')], default='other', max_length=30)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='organizations.organization')),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='cultures.thermalzone')),
            ],
        ),
        migrations.CreateModel(
            name='SalinityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField()),
                ('salinity_psu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salinity_measurements', to='cultures.thermalzone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_measurements', to='measurements.probe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='ThermalAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reference_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_deviation_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_anomalies', to='cultures.thermalzone')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField()),
                ('polyp_count', models.PositiveIntegerField(default=0)),
                ('ephyrae_count', models.PositiveIntegerField(default=0)),
                ('strobila_count', models.PositiveIntegerField(default=0)),
                ('culture_status', models.CharField(choices=[('good', 'Good'), ('medium', 'Medium'), ('bad', 'Bad'), ('dead', 'Dead'), ('not_specified', 'Not specified')], default='not_specified', max_length=30)),
                ('needs_attention', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biological_measurements', to='cultures.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on', '-created_at'],
                'indexes': [models.Index(fields=['box', 'measured_on'], name='measurement_box_id_49b849_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_count', models.PositiveIntegerField(default=0)),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_temperatures', to='cultures.thermalzone')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('thermal_zone', 'date'), name='unique_daily_temperature_per_zone_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='probe',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_probe_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='salinitymeasurement',
            constraint=models.UniqueConstraint(fields=('thermal_zone', 'measured_on'), name='unique_salinity_measurement_per_zone_date'),
        ),
        migrations.AddIndex(
            model_name='temperaturemeasurement',
            index=models.Index(fields=['measured_at'], name='measurement_measure_b1beed_idx'),
        ),
        migrations.AddConstraint(
            model_name='temperaturemeasurement',
            constraint=models.UniqueConstraint(fields=('probe', 'measured_at'), name='unique_temperature_measurement_per_probe_date'),
        ),
    ]
