# Generated by Django 5.2.13 on 2026-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalmeasurement',
            name='culture_status',
            field=models.CharField(choices=[('good', 'Bon'), ('medium', 'Moyen'), ('bad', 'Mauvais'), ('dead', 'Mort'), ('not_specified', 'Non précisé')], default='not_specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_type',
            field=models.CharField(choices=[('general', 'Générale'), ('contamination', 'Contamination'), ('subculture_needed', 'Repiquage à prévoir'), ('mortality', 'Mortalité'), ('other', 'Autre')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='probe',
            name='probe_type',
            field=models.CharField(choices=[('lorawan', 'LoRaWAN'), ('iminilide', 'iMinilide'), ('manual', 'Saisie manuelle'), ('other', 'Autre')], default='other', max_length=30),
        ),
    ]
