# Generated by Django 5.2.13 on 2026-07-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_biologicalmeasurement_culture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalmeasurement',
            name='salinity_psu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
