# Generated by Django 5.2.17 on 2026-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_biologicalmeasurement_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalmeasurement',
            name='polyp_state_sequence',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
