# Generated by Django 5.2.17 on 2026-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_quantitative_subculture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalmeasurement',
            name='strobila_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
