# Generated by Django 5.2.13 on 2026-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Creation'), ('update', 'Update'), ('archive', 'Archive'), ('entry', 'Entry'), ('subculture', 'Subculture'), ('transfer', 'Transfer'), ('import', 'Import'), ('export', 'Export'), ('scan', 'Scan'), ('view', 'View'), ('login', 'Login')], max_length=40),
        ),
    ]
