# Generated by Django 5.2.13 on 2026-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('lab_technician', 'Technicien laboratoire'), ('viewer', 'Lecture seule')], default='viewer', max_length=30),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='interface_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=5),
        ),
    ]
