# Generated by Django 5.2.17 on 2026-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organizationmembership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('key_hash', models.CharField(max_length=64)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='accounts_auth_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='unique_authentication_throttle_key')],
            },
        ),
    ]
