# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_email_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="is_responsable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_responsable", False),
                    ("role", "admin"),
                    _connector="OR",
                ),
                name="responsable_requires_admin_role",
            ),
        ),
    ]
