# Generated by Django 5.2.17 on 2026-10-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationmembership_is_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='is_hidden_from_team',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='accounts.organizationmembership')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('expires_at__isnull', True), ('issued_at__isnull', True)), models.Q(('expires_at__isnull', False), ('issued_at__isnull', False)), _connector='OR'), name='account_invitation_issue_times_together')],
            },
        ),
    ]
