# Generated by Django 5.2.13 on 2026-05-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('field_collection', 'Field collection'), ('reproduction', 'Reproduction'), ('donation', 'Donation'), ('exchange', 'Exchange'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('origin_institution_name', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('technicians', models.CharField(blank=True, max_length=250)),
                ('technique', models.CharField(blank=True, max_length=250)),
                ('partner_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.partnerinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('rank', models.CharField(blank=True, max_length=80)),
                ('worms_aphia_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=150)),
                ('genus_species_code', models.CharField(blank=True, max_length=12)),
                ('worms_aphia_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_described', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('origin_code', models.CharField(blank=True, max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.origin')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strains', to='taxonomy.species')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('species', 'code'), name='unique_strain_per_species')],
            },
        ),
    ]
