# Generated by Django 5.2.13 on 2026-08-04 11:45

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_french_species_names(apps, schema_editor):
    Species = apps.get_model('taxonomy', 'Species')
    SpeciesTranslation = apps.get_model('taxonomy', 'SpeciesTranslation')
    translations = [
        SpeciesTranslation(
            species_id=species.id,
            language_code='fr',
            name=species.common_name,
        )
        for species in Species.objects.exclude(common_name='')
    ]
    SpeciesTranslation.objects.bulk_create(translations, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='taxonomy.species')),
            ],
            options={
                'ordering': ['language_code'],
                'constraints': [models.UniqueConstraint(fields=('species', 'language_code'), name='unique_species_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='StrainTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='taxonomy.strain')),
            ],
            options={
                'ordering': ['language_code'],
                'constraints': [models.UniqueConstraint(fields=('strain', 'language_code'), name='unique_strain_translation_per_language')],
            },
        ),
        migrations.RunPython(
            copy_existing_french_species_names,
            migrations.RunPython.noop,
        ),
    ]
