# Generated by Django 5.2.17 on 2026-09-25 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_speciestranslation_straintranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStrainIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='strain',
            name='global_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strains', to='taxonomy.globalstrainidentity'),
        ),
    ]
