# Generated by Django 5.2.17 on 2026-09-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('taxonomy', '0003_globalstrainidentity_strain_global_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strains', to='organizations.organization'),
        ),
    ]
