# Generated by Django 5.2.17 on 2026-09-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('taxonomy', '0004_strain_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProvenanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('biological_provenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_code_assignments', to='taxonomy.biologicalprovenance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenance_code_assignments', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'biological_provenance'), name='unique_provenance_code_per_organization_source'), models.UniqueConstraint(fields=('organization', 'code'), name='unique_provenance_code_per_organization_code')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpeciesCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_code_assignments', to='organizations.organization')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_code_assignments', to='taxonomy.species')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'species'), name='unique_species_code_per_organization_species'), models.UniqueConstraint(fields=('organization', 'code'), name='unique_species_code_per_organization_code')],
            },
        ),
    ]
