# Generated by Django 5.2.17 on 2026-09-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_biologicalprovenance_organizationprovenancecode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalStrainIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_strain_identities', to='taxonomy.organizationspeciescode')),
                ('strain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='local_identity', to='taxonomy.strain')),
            ],
        ),
    ]
