# Generated by Django 5.2.17 on 2026-09-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_localstrainidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstrainidentity',
            name='provenance_code_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_strain_identities', to='taxonomy.organizationprovenancecode'),
        ),
    ]
