# Generated by Django 5.2.17 on 2026-10-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('taxonomy', '0008_strain_canonical_global_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalStrainNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('biological_provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_strain_number_counters', to='taxonomy.biologicalprovenance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_strain_number_counters', to='organizations.organization')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_strain_number_counters', to='taxonomy.species')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('biological_provenance__isnull', False)), fields=('organization', 'species', 'biological_provenance'), name='unique_local_x_scope'), models.UniqueConstraint(condition=models.Q(('biological_provenance__isnull', True)), fields=('organization', 'species'), name='unique_local_x_null_scope')],
            },
        ),
    ]
