# Generated by Django 5.2.13 on 2026-05-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('can_view_inventory', models.BooleanField(default=True)),
                ('can_view_measurements', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_sharing_agreements', to='organizations.organization')),
                ('partner_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_sharing_agreements', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_organization', 'partner_organization'), name='unique_sharing_agreement_between_organizations'), models.CheckConstraint(condition=models.Q(('owner_organization', models.F('partner_organization')), _negated=True), name='sharing_agreement_uses_two_organizations')],
            },
        ),
    ]
